name: hola Mundo # Nombre del workflow

#on: [push, pull_request] # Evento que se dispara al hacer un push
on: # Evento que se dispara al hacer un push o pull request en la rama main
    push:
        branches:
          - main

    pull_request:
        branches:
          - main

jobs: #lo que queremos ejecutar, se realiza dentro de un servidor
  hola: #nombre del job
    runs-on: ubuntu-latest # servidor
    steps: #pasos, unidad mas pequeña de un job
      - name: hola Mundo #nombre del paso
        run: echo "Hola Mundo" #comando a ejecutar

      - name: touch file
        run: touch file.txt

      - name: Set text
        run: echo "Hola mundo" > hola.txt

      - name: Read file
        run: cat hola.txt

  listar:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: listar archivos
        run: ls -al
