name: hola Mundo # Nombre del workflow

on: [push] # Evento que se dispara al hacer un push

jobs: #lo que queremos ejecutar, se realiza dentro de un servidor
  hola: #nombre del job
    runs-on: ubuntu-latest # servidor
    steps: #pasos, unidad mas pequeña de un job
      - name: hola Mundo #nombre del paso
        run: echo "Hola Mundo" #comando a ejecutar

      - name: touch file
        run: touch file.txt

      - name: Set text
        run: echo "Hola mundo" > hola.txt

      - name: Read file
        run: cat hola.txt

  listar:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
      - name: listar archivos
        run: ls -al
